# Import libraries

In [3]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder
# conda install -c conda-forge mlxtend

In [7]:
movie= pd.read_csv("C:\\Users\\Mohan Kumar\\Desktop\\EXCELR\\DATA SETS\\association rules\\my_movies.csv")
movie.head()

,V1,V2,V3,V4,V5,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile
0,Sixth Sense,LOTR1,Harry Potter1,Green Mile,LOTR2,1,0,1,1,0,1,0,0,0,1
1,Gladiator,Patriot,Braveheart,NaN,NaN,0,1,0,0,1,0,0,0,1,0
2,LOTR1,LOTR2,NaN,NaN,NaN,0,0,1,0,0,1,0,0,0,0
3,Gladiator,Patriot,Sixth Sense,NaN,NaN,1,1,0,0,1,0,0,0,0,0
4,Gladiator,Patriot,Sixth Sense,NaN,NaN,1,1,0,0,1,0,0,0,0,0

# Pre-Processing
As the data is not in transaction formation 
We are using transaction Encoder

In [9]:
df=pd.get_dummies(movie)
df.head()

,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile,...,V2_LOTR,V2_LOTR1,V2_LOTR2,V2_Patriot,V3_Braveheart,V3_Gladiator,V3_Harry Potter1,V3_Sixth Sense,V4_Green Mile,V5_LOTR2
0,1,0,1,1,0,1,0,0,0,1,...,0,1,0,0,0,0,1,0,1,1
1,0,1,0,0,1,0,0,0,1,0,...,0,0,0,1,1,0,0,0,0,0
2,0,0,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
4,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0

In [10]:
df.isnull().sum()

Sixth Sense         0
Gladiator           0
LOTR1               0
Harry Potter1       0
Patriot             0
LOTR2               0
Harry Potter2       0
LOTR                0
Braveheart          0
Green Mile          0
V1_Gladiator        0
V1_Harry Potter1    0
V1_LOTR1            0
V1_Sixth Sense      0
V2_Harry Potter2    0
V2_LOTR             0
V2_LOTR1            0
V2_LOTR2            0
V2_Patriot          0
V3_Braveheart       0
V3_Gladiator        0
V3_Harry Potter1    0
V3_Sixth Sense      0
V4_Green Mile       0
V5_LOTR2            0
dtype: int64

In [11]:
df.shape

(10, 25)

In [12]:
def encode_units(x):
    if x<=0:
        return 0
    if x>=1:
        return 1
book=df.applymap(encode_units)
book

,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile,...,V2_LOTR,V2_LOTR1,V2_LOTR2,V2_Patriot,V3_Braveheart,V3_Gladiator,V3_Harry Potter1,V3_Sixth Sense,V4_Green Mile,V5_LOTR2
0,1,0,1,1,0,1,0,0,0,1,...,0,1,0,0,0,0,1,0,1,1
1,0,1,0,0,1,0,0,0,1,0,...,0,0,0,1,1,0,0,0,0,0
2,0,0,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
4,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
5,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
6,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
9,1,1,0,0,0,0,0,1,0,1,...,1,0,0,0,0,1,0,0,1,0

# Apriori Algorithm

In [16]:
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#rules = association_rules(frequent_itemsets, metric='lift',min_threshold=1)
frequent_itemsets
#rules.head()

    support                                        itemsets
0       0.6                                   (Sixth Sense)
1       0.7                                     (Gladiator)
2       0.6                                       (Patriot)
3       0.6                                  (V1_Gladiator)
4       0.6                                    (V2_Patriot)
5       0.6                            (Patriot, Gladiator)
6       0.6                       (V1_Gladiator, Gladiator)
7       0.6                         (V2_Patriot, Gladiator)
8       0.6                         (Patriot, V1_Gladiator)
9       0.6                           (Patriot, V2_Patriot)
10      0.6                      (V2_Patriot, V1_Gladiator)
11      0.6              (Patriot, V1_Gladiator, Gladiator)
12      0.6                (Patriot, V2_Patriot, Gladiator)
13      0.6           (V1_Gladiator, V2_Patriot, Gladiator)
14      0.6             (Patriot, V2_Patriot, V1_Gladiator)
15      0.6  (Patriot, V1_Gladiator, V2_Patriot, Gladiator)

In [20]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
1,(Gladiator),(Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
2,(V1_Gladiator),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
3,(Gladiator),(V1_Gladiator),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
4,(V2_Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
5,(Gladiator),(V2_Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
6,(Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
7,(V1_Gladiator),(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
8,(Patriot),(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
9,(V2_Patriot),(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
10,(V2_Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
11,(V1_Gladiator),(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
12,"(Patriot, V1_Gladiator)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
13,"(Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
14,"(Gladiator, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
15,(Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
16,(V1_Gladiator),"(Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
17,(Gladiator),"(Patriot, V1_Gladiator)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
18,"(Patriot, V2_Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
19,"(Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
20,"(V2_Patriot, Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
21,(Patriot),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
22,(V2_Patriot),"(Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
23,(Gladiator),"(Patriot, V2_Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
24,"(V2_Patriot, V1_Gladiator)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
25,"(Gladiator, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
26,"(V2_Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
27,(V1_Gladiator),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
28,(V2_Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
29,(Gladiator),"(V2_Patriot, V1_Gladiator)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
30,"(Patriot, V2_Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
31,"(Patriot, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
32,"(V2_Patriot, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
33,(Patriot),"(V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
34,(V2_Patriot),"(Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
35,(V1_Gladiator),"(Patriot, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
36,"(Patriot, V2_Patriot, V1_Gladiator)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
37,"(Patriot, Gladiator, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
38,"(Patriot, V2_Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
39,"(Gladiator, V2_Patriot, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
40,"(Patriot, V1_Gladiator)","(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
41,"(Patriot, V2_Patriot)","(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
42,"(Patriot, Gladiator)","(V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
43,"(V2_Patriot, V1_Gladiator)","(Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
44,"(Gladiator, V1_Gladiator)","(Patriot, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
45,"(V2_Patriot, Gladiator)","(Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
46,(Patriot),"(Gladiator, V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
47,(V1_Gladiator),"(Patriot, V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
48,(V2_Patriot),"(Patriot, Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
49,(Gladiator),"(Patriot, V2_Patriot, V1_Gladiator)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8

#####  An leverage value of 0 indicates independence. Range will be [-1 1]
A high conviction value means that the consequent is highly depending on the antecedent and range [0 inf]

In [24]:
#rules[(rules['lift']>=6)&
#     (rules['confidence']>=0.8)]
rules.sort_values('lift',ascending = True)[0:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
36,"(Patriot, V2_Patriot, V1_Gladiator)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
18,"(Patriot, V2_Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
12,"(Patriot, V1_Gladiator)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
24,"(V2_Patriot, V1_Gladiator)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
4,(V2_Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
2,(V1_Gladiator),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
5,(Gladiator),(V2_Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
1,(Gladiator),(Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
29,(Gladiator),"(V2_Patriot, V1_Gladiator)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
23,(Gladiator),"(Patriot, V2_Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
17,(Gladiator),"(Patriot, V1_Gladiator)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
49,(Gladiator),"(Patriot, V2_Patriot, V1_Gladiator)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
3,(Gladiator),(V1_Gladiator),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
33,(Patriot),"(V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
34,(V2_Patriot),"(Patriot, V1_Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
35,(V1_Gladiator),"(Patriot, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
6,(Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
37,"(Patriot, Gladiator, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
38,"(Patriot, V2_Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf

In [33]:
rules[rules.lift>1.6]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
6,(Patriot),(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
7,(V1_Gladiator),(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
8,(Patriot),(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
9,(V2_Patriot),(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
10,(V2_Patriot),(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
11,(V1_Gladiator),(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
13,"(Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
14,"(Gladiator, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
15,(Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
16,(V1_Gladiator),"(Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
19,"(Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
20,"(V2_Patriot, Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
21,(Patriot),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
22,(V2_Patriot),"(Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
25,"(Gladiator, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
26,"(V2_Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
27,(V1_Gladiator),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
28,(V2_Patriot),"(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
30,"(Patriot, V2_Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
31,"(Patriot, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
32,"(V2_Patriot, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
33,(Patriot),"(V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
34,(V2_Patriot),"(Patriot, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
35,(V1_Gladiator),"(Patriot, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
37,"(Patriot, Gladiator, V1_Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
38,"(Patriot, V2_Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
39,"(Gladiator, V2_Patriot, V1_Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
40,"(Patriot, V1_Gladiator)","(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
41,"(Patriot, V2_Patriot)","(Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
42,"(Patriot, Gladiator)","(V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
43,"(V2_Patriot, V1_Gladiator)","(Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
44,"(Gladiator, V1_Gladiator)","(Patriot, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
45,"(V2_Patriot, Gladiator)","(Patriot, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
46,(Patriot),"(Gladiator, V2_Patriot, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
47,(V1_Gladiator),"(Patriot, V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
48,(V2_Patriot),"(Patriot, Gladiator, V1_Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf